# 1번

In [112]:
import numpy as np

In [113]:
#넘파이 배열 생성
array1 = np.array([[-6, 4, 2, 3]])
array2 = np.array([[7, 8, -3, 6]])

In [114]:
#차원변화
array1 = np.reshape(array1, [2,2])
array2 = np.reshape(array2, [2,2])
array1

array([[-6,  4],
       [ 2,  3]])

In [115]:
array_1_t = np.transpose(array1) #전치행렬
array_1_t

array([[-6,  2],
       [ 4,  3]])

In [116]:
#행렬 연산
r1 =np.matmul(array_1_t, array2)
r2 =np.matmul(array2, array_1_t)
r1,r2

(array([[-48, -36],
        [ 19,  50]]), array([[-10,  38],
        [ 42,  12]]))

# 2번

In [117]:
import pandas as pd

In [118]:
score = pd.Series([50,90,80,70]).astype(float) #float tpye으로 시리즈 생성
score

0    50.0
1    90.0
2    80.0
3    70.0
dtype: float64

In [119]:
score[0] = 100 #100으로 교체
score

0    100.0
1     90.0
2     80.0
3     70.0
dtype: float64

In [120]:
score[0], score[1]

(100.0, 90.0)

In [121]:
score[[0,2]]

0    100.0
2     80.0
dtype: float64

In [122]:
score[0:3:2] #슬라이싱

0    100.0
2     80.0
dtype: float64

# 3번

In [123]:
df = np.array([[2001,1987,2005],[1,2,3],[3,1,2]])
df

array([[2001, 1987, 2005],
       [   1,    2,    3],
       [   3,    1,    2]])

In [124]:
df = pd.DataFrame(df, index = ['설립연도','순위','만족도'], columns = ['세종대','서울대','시립대'])
df #df로 변환

세종대   서울대   시립대
설립연도  2001  1987  2005
순위       1     2     3
만족도      3     1     2

In [125]:
dic = {'세종대' : [2001,1,3], '서울대' : [1987,2,1] , '시립대' : [2005,3,2]} 
dic #dic 생성

{'세종대': [2001, 1, 3], '서울대': [1987, 2, 1], '시립대': [2005, 3, 2]}

In [126]:
dic_to_df = pd.DataFrame(dic,index = ['설립연도', '순위','만족도'])
dic_to_df

세종대   서울대   시립대
설립연도  2001  1987  2005
순위       1     2     3
만족도      3     1     2

# 4번

In [127]:
df1 = np.array([[35,42,49, 56],[63,70,77,84],[91,98,105,112],[119,126,133,140]])
df2 = np.array([[5,10,15,20],[25,30,35,40],[45,50,55,60],[65,70,75,80]])
df1 = pd.DataFrame(df1, index = ['서울','경기도','강원도','부산'], columns = ['고진영','윤수경','양지윤','박시현'])
df2 = pd.DataFrame(df2, index = ['서울','경주','인천','강원도'], columns = ['박시현', '최규민', '이용빈', '양지윤'])

In [128]:
df1

고진영  윤수경  양지윤  박시현
서울    35   42   49   56
경기도   63   70   77   84
강원도   91   98  105  112
부산   119  126  133  140

In [129]:
df2

박시현  최규민  이용빈  양지윤
서울     5   10   15   20
경주    25   30   35   40
인천    45   50   55   60
강원도   65   70   75   80

In [130]:
#add함수
df3 = df1.add(df2)
df3

고진영    박시현    양지윤  윤수경  이용빈  최규민
강원도  NaN  177.0  185.0  NaN  NaN  NaN
경기도  NaN    NaN    NaN  NaN  NaN  NaN
경주   NaN    NaN    NaN  NaN  NaN  NaN
부산   NaN    NaN    NaN  NaN  NaN  NaN
서울   NaN   61.0   69.0  NaN  NaN  NaN
인천   NaN    NaN    NaN  NaN  NaN  NaN

In [131]:
#sub 함수
df3 = df1.sub(df2, fill_value= 50)
df3

고진영   박시현   양지윤   윤수경   이용빈   최규민
강원도  41.0  47.0  25.0  48.0 -25.0 -20.0
경기도  13.0  34.0  27.0  20.0   NaN   NaN
경주    NaN  25.0  10.0   NaN  15.0  20.0
부산   69.0  90.0  83.0  76.0   NaN   NaN
서울  -15.0  51.0  29.0  -8.0  35.0  40.0
인천    NaN   5.0 -10.0   NaN  -5.0   0.0